-- CreateEnum
CREATE TYPE "Mask" AS ENUM ('SQUIRCLE', 'HEART', 'HEXASIDE', 'HEXAVERT', 'DECAGON', 'PENTAGON', 'DIAMOND', 'SQUARE', 'CIRCLE', 'PARALITH', 'PARALOGLIDE', 'PARALLELOZEN', 'PARALLELOSURF', 'STARMI', 'STARYU', 'TRIADIX', 'TRINEON', 'TRIQUARK', 'TRIFLUX');

-- AlterTable
ALTER TABLE "UserProfile" ADD COLUMN     "mask" "Mask" DEFAULT 'HEXAVERT',
ALTER COLUMN "bio" SET DEFAULT '',
ALTER COLUMN "profilePictureUrl" SET DEFAULT '',
ALTER COLUMN "headerImageUrl" SET DEFAULT '',
ALTER COLUMN "name" SET DEFAULT '',
ALTER COLUMN "city" SET DEFAULT '';
